services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: cicd
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d cicd"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    command: npm run start:api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/cicd
      # POSTGRES_HOST: postgres
      # POSTGRES_PORT: 5432
      # POSTGRES_DB: cicd
      # POSTGRES_USER: admin
      # POSTGRES_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy

  worker-1:
    build: .
    command: npm run start:worker
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/cicd
    depends_on:
      postgres:
        condition: service_healthy

  worker-2:
    build: .
    command: npm run start:worker
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/cicd
    depends_on:
      postgres:
        condition: service_healthy

  worker-3:
    build: .
    command: npm run start:worker
    environment:
      DATABASE_URL: postgresql://admin:password@postgres:5432/cicd
    depends_on:
      postgres:
        condition: service_healthy
